Viho/Controllers/TbSales1Controller.cs
using System;
using System.Collections.Generic;
using System.Drawing.Imaging;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.StaticFiles;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Viho.web.DataDB;


namespace Viho.web.Controllers
{
    public class TbSales1Controller : Controller
    {
        private readonly DbRentalContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public TbSales1Controller(DbRentalContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: TbSales1
        public async Task<IActionResult> Index()
        {
            var sales = await _context.TbSales.ToListAsync();
            return View(sales);
        }

        // GET: TbSales1/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.TbSales == null)
            {
                return NotFound();
            }

            var tbSale = await _context.TbSales
                .FirstOrDefaultAsync(m => m.SId == id);
            if (tbSale == null)
            {
                return NotFound();
            }

            return View(tbSale);
        }

        // GET: TbSales1/Create
        public async Task<IActionResult> Create()
        {
            ViewBag.CategoryList = await GetCategoryListAsync();
            ViewBag.TransactionTypeList = await GetTransactionTypeListAsync();

            return View();
        }

        // POST: TbSales1/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SId,SDate,SCategory,STransactionType,SDetail,SAmountIn,SAmountOut,SReceipt,ReceiptFile")] TbSale tbSale, IFormFile? SReceipt)
        {
            if (ModelState.IsValid)
            {
                if (SReceipt != null && SReceipt.Length > 0)
                {
                    string uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "Picture/Receipt/");
                    string uniqueFileName = Guid.NewGuid().ToString() + "_" + SReceipt.FileName;
                    string filePath = Path.Combine(uploadsFolder, uniqueFileName);

                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        await SReceipt.CopyToAsync(fileStream);
                    }

                    tbSale.SReceipt = uniqueFileName;
                }

                _context.Add(tbSale);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            ViewBag.CategoryList = await GetCategoryListAsync();
            ViewBag.TransactionTypeList = await GetTransactionTypeListAsync();
            return View(tbSale);
        }

        // GET: TbSales1/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tbSale = await _context.TbSales.FindAsync(id);
            if (tbSale == null)
            {
                return NotFound();
            }

            ViewBag.CategoryList = await GetCategoryListAsync();
            ViewBag.TransactionTypeList = await GetTransactionTypeListAsync();
            ViewBag.ExistingReceiptFileName = tbSale.SReceipt; // Set the existing receipt file name in ViewBag

            return View(tbSale);
        }

            // POST: TbSales1/Edit/5
            // To protect from overposting attacks, enable the specific properties you want to bind to.
            // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
         [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SId,SDate,SCategory,STransactionType,SDetail,SAmountIn,SAmountOut,SReceipt,ReceiptFile")] TbSale tbSale, IFormFile SReceipt)
        {
            if (id != tbSale.SId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {

                    if (SReceipt != null && SReceipt.Length > 0)
                    {
                        string uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "Picture/Receipt/");

                        if (!string.IsNullOrEmpty(tbSale.SReceipt))
                        {
                            string previousFilePath = Path.Combine(uploadsFolder, tbSale.SReceipt);
                            if (System.IO.File.Exists(previousFilePath))
                            {
                                System.IO.File.Delete(previousFilePath);
                            }
                        }

                        string uniqueFileName = Guid.NewGuid().ToString() + "_" + SReceipt.FileName;
                        string filePath = Path.Combine(uploadsFolder, uniqueFileName);

                        using (var fileStream = new FileStream(filePath, FileMode.Create))
                        {
                            await SReceipt.CopyToAsync(fileStream);
                        }

                        // Update the image property
                        tbSale.SReceipt = uniqueFileName;
                    }

                    _context.Update(tbSale);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TbSaleExists(id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            ViewBag.CategoryList = await GetCategoryListAsync();
            ViewBag.TransactionTypeList = await GetTransactionTypeListAsync();
            ViewBag.ExistingReceiptFileName = tbSale.SReceipt;// Set the existing receipt file name in ViewBag

            return View(tbSale);
        }


        // GET: TbSales1/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tbSale = await _context.TbSales.FindAsync(id);
            if (tbSale == null)
            {
                return NotFound();
            }

            return View(tbSale);
        }


        // POST: TbSales1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tbSale = await _context.TbSales.FindAsync(id);
            if (tbSale == null)
            {
                return NotFound();
            }

            // Delete the image file if it exists
            if (!string.IsNullOrEmpty(tbSale.SReceipt))
            {
                string imagePath = Path.Combine(_webHostEnvironment.WebRootPath, "Picture/Receipt", tbSale.SReceipt);

                // Check if the image file exists before deleting
                if (System.IO.File.Exists(imagePath))
                {
                    System.IO.File.Delete(imagePath);
                }
            }

            _context.TbSales.Remove(tbSale);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TbSaleExists(int id)
        {
          return (_context.TbSales?.Any(e => e.SId == id)).GetValueOrDefault();
        }

        private static Task<List<SelectListItem>> GetCategoryListAsync()
        {
            var categoryList = new List<SelectListItem>
            {
                new SelectListItem { Value = "General", Text = "General" },
                new SelectListItem { Value = "GE1", Text = "GE1" },
                new SelectListItem { Value = "GE2", Text = "GE2" },
                new SelectListItem { Value = "GE3", Text = "GE3" },
                new SelectListItem { Value = "TN1", Text = "TN1" },
                new SelectListItem { Value = "TN2", Text = "TN2" },
                new SelectListItem { Value = "TN3", Text = "TN3" },
                new SelectListItem { Value = "TN4", Text = "TN4" }
            };

            return Task.FromResult(categoryList);
        }

        private static Task<List<SelectListItem>> GetTransactionTypeListAsync()
        {
            var transactionTypeList = new List<SelectListItem>
            {
                new SelectListItem { Value = "Cash", Text = "Cash" },
                new SelectListItem { Value = "Credit Card", Text = "Credit Card" },
                new SelectListItem { Value = "Bank Transfer", Text = "Bank Transfer" },
            };

            return Task.FromResult(transactionTypeList);
        }

        // GET: TbSales1/DownloadReceipt/5
        public async Task<IActionResult> DownloadReceipt(int id)
        {
            var sale = await _context.TbSales.FindAsync(id);
            if (sale == null || string.IsNullOrEmpty(sale.SReceipt))
            {
                return NotFound();
            }

            // Get the file path
            string filePath = Path.Combine(_webHostEnvironment.WebRootPath, "Picture/Receipt", sale.SReceipt);

            // Check if the file exists
            if (!System.IO.File.Exists(filePath))
            {
                return NotFound();
            }

            // Set the appropriate content type based on the file extension

Viho/Views/TbSales1/Delete.cshtml
@model Viho.web.DataDB.TbSale

@{
    ViewData["Title"] = "Expenses Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="page-body">
    <div class="container-fluid">
        <div class="page-header">
            <div class="row">
                <div class="col-sm-6">
                    <h3>Expenses Records</h3>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a asp-controller="Dashboard" asp-action="Index">Home</a></li>
                        <li class="breadcrumb-item">Expenses</li>
                        <li class="breadcrumb-item active">Delete Expenses</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <!-- Container-fluid starts-->
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header pb-0">
                        <h5>Delete Confirmation</h5>
                        <span><a asp-action="Index">Back to List</a></span>
                    </div>
                    <div class="card-body">
                        <div>
                            <h5 style="color: red;">Are you sure you want to delete this?</h5>
                            <hr />
                            <dl class="row">
                                <dt class="col-sm-2">
                                    @Html.DisplayName("Date")
                                </dt>
                                <dd class="col-sm-10">
                                    : @Html.DisplayFor(model => model.SDate)
                                </dd>
                                <dt class="col-sm-2">
                                    @Html.DisplayName("Category")
                                </dt>
                                <dd class="col-sm-10">
                                    : @Html.DisplayFor(model => model.SCategory)
                                </dd>
                                <dt class="col-sm-2">
                                    @Html.DisplayName("Transaction Type")
                                </dt>
                                <dd class="col-sm-10">
                                    : @Html.DisplayFor(model => model.STransactionType)
                                </dd>
                                <dt class="col-sm-2">
                                    @Html.DisplayName("Detail")
                                </dt>
                                <dd class="col-sm-10">
                                    : @Html.DisplayFor(model => model.SDetail)
                                </dd>
                                <dt class="col-sm-2">
                                    @Html.DisplayName("Amount In")
                                </dt>
                                <dd class="col-sm-10">
                                    : @Html.DisplayFor(model => model.SAmountIn)
                                </dd>
                                <dt class="col-sm-2">
                                    @Html.DisplayName("Amount Out")
                                </dt>
                                <dd class="col-sm-10">
                                    : @Html.DisplayFor(model => model.SAmountOut)
                                </dd>
                                <dt class="col-sm-2">
                                    @Html.DisplayName("Receipt")
                                </dt>
                                <dd class="col-sm-10">
                                    @if (!string.IsNullOrEmpty(Model.SReceipt))
                                    {
                                        <img src="@Url.Content("~/Picture/Receipt/" + Model.SReceipt)" alt="Receipt" style="max-width: 300px; max-height: 300px;" />
                                        <hr />
                                        <a href="@Url.Action("DownloadReceipt", "TbSales1", new { id=Model.SId })">Download</a>
                                    }
                                    else
                                    {
                                        <span>No Receipt</span>
                                    }
                                </dd>
                            </dl>
                            <form asp-action="Delete" onsubmit="return confirmDelete();">
                                <input type="hidden" asp-for="SId" />
                                <input type="submit" value="Delete" class="btn btn-danger col-sm-12" />
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Container-fluid Ends-->
</div>
@section Script{
    <script>
        function confirmDelete() {
            if (confirm("Deleting this can't be undone, are you sure?")) {
                return true;
            } else {
                return false;
            }
        }
    </script>
}

Viho/Views/TbSales1/Details.cshtml
<!-- Container-fluid starts-->
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">

                <div class="card-body">
                    <div class="row">
                        <hr />
                        <p><b>Date:</b> @Model.SDate</p>
                        <p><b>Category:</b> @Model.SCategory</p>
                        <p><b>Transaction Type:</b> @Model.STransactionType</p>
                        <p><b>Detail:</b> @Model.SDetail</p>
                        <p><b>Amount In: RM</b> @Model.SAmountIn</p>
                        <p><b>Amount Out: RM</b> @Model.SAmountOut</p>
                        <p><b>Receipt:</b> 
                            @if (!string.IsNullOrEmpty(Model.SReceipt))
                            {
                                <a href="@Url.Action("DownloadReceipt", "TbSales1", new { id =Model.SId })">Download</a>
                                <hr />
                                <img src="@Url.Content("~/Picture/Receipt/" + Model.SReceipt)" alt="Receipt" style="max-width: 300px; max-height: 300px;" />

                            }
                            else
                            {
                                <span>No Receipt</span>
                            }
                        </p>
                        <p><a class="btn btn-secondary" asp-action="Edit" asp-route-id="@Model?.SId">Edit</a></p>
                        <hr />
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

Viho/Views/TbSales1/Index.cshtml
@model IEnumerable<Viho.web.DataDB.TbSale>

@{
    ViewData["Title"] = "Expense";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var userRoleIdClaim = User.Claims.FirstOrDefault(c => c.Type == "URoleid");
    var userRoleId = userRoleIdClaim != null ? int.Parse(userRoleIdClaim.Value) : 0;
}

<div class="page-body">
    <div class="container-fluid">
        <div class="page-header">
            <div class="row">
                <div class="col-sm-6">
                    <h3>Expenses</h3>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a asp-controller="Dashboard" asp-action="Index">Home</a></li>
                        <li class="breadcrumb-item active">Expenses</li>
                    </ol>
                </div>
                @if (userRoleId == 3)
                {
                    <div class="col-sm-6">
                        <!-- Create new Start-->
                        <div class="bookmark">
                            <ul>
                                <a asp-action="Create" class="btn btn-pill btn-primary btn-air-primary btn-primary-gradien"><i class="fa fa-plus-square"></i> Add New Record</a>
                            </ul>
                        </div>
                        <!-- Create new Ends-->
                    </div>
                }else{}
            </div>
        </div>
    </div>
    <!-- Container-fluid starts-->
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <h5>Sales Record</h5><span>View Expenses Records</span>
                        <br />
                        <div class="col-sm-4 text-right">
                            <div class="form-group">
                                <label for="categoryFilter">Filter by Category:</label>
                                <select id="categoryFilter" class="form-control">
                                    <option value="">All Categories</option>
                                    @foreach (var category in Model.Select(s => s.SCategory).Distinct())
                                    {
                                        <option value="@category">@category</option>
                                    }
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="dt-ext table-responsive">
                            <table class="display" id="responsive">
                                <thead>
                                    <tr>
                                        <th scope="col">Date</th>
                                        <th scope="col">Category</th>
                                        <th scope="col">Transaction Type</th>
                                        <th scope="col">Detail</th>
                                        <th scope="col">Amount In</th>
                                        <th scope="col">Amount Out</th>
                                        <th scope="col">Receipt</th>
                                        <th scope="col">Actions</th>
                                    </tr>
                                </thead>
                                <tbody id="salesTableBody">
                                    @foreach (var item in Model)
                                    {
                                        <tr class="data-row">
                                            <td>@item.SDate</td>
                                            <td class="category">@item.SCategory</td>
                                            <td>@item.STransactionType</td>
                                            <td>@item.SDetail</td>
                                            <td>@item.SAmountIn</td>
                                            <td>@item.SAmountOut</td>
                                            <td>
                                                @if (!string.IsNullOrEmpty(item.SReceipt))
                                                {
                                                    <a href="@Url.Action("DownloadReceipt", "TbSales1", new { id = item.SId })">Download</a>
                                                }
                                                else
                                                {
                                                    <span>No Receipt</span>
                                                }
                                            </td>
                                            <td>
                                                @if(userRoleId == 3){
                                                <a asp-action="Edit" asp-route-id="@item.SId" class="icofont icofont-edit-alt">Edit</a><br>
                                                <a class="icofont icofont-file-alt" onclick="loadDetails(@item.SId)">View</a><br>
                                                    <a asp-action="Delete" asp-route-id="@item.SId" class="icofont icofont-ui-delete">Delete</a>
                                                }
                                                else
                                                {
                                                <a class="icofont icofont-file-alt" onclick="loadDetails(@item.SId)">View</a><br>
                                                }                                            
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!---container fluid end-->
    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Detail of Record</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body" id="modalContent">
                    <div class="card">
                        <div class="animate-widget">
                            <!-- Content will be loaded dynamically here -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Script{

    <script>
        function loadDetails(id) {
            $.ajax({
                url: '@Url.Action("Details", "TbSales1")',
                type: 'GET',
                data: { id: id },
                success: function (result) {
                    $('#modalContent').html(result);
                    $('#myModal').modal('show');
                },
                error: function () {
                    alert('Error occurred while loading details.');
                }
            });
        }
    </script>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function () {
            // Handle category filter change event
            $('#categoryFilter').change(function () {
                var selectedCategory = $(this).val();
                filterTableByCategory(selectedCategory);
            });

            // Function to filter the table by category
            function filterTableByCategory(category) {
                // Show all rows if category is empty
                if (!category) {
                    $('#salesTableBody tr').show();
                } else {
                    // Hide rows that don't match the selected category
                    $('#salesTableBody tr').each(function () {
                        var rowCategory = $(this).find('.category').text().trim();
                        if (rowCategory !== category) {
                            $(this).hide();
                        } else {
                            $(this).show();
                        }
                    });
                }
            }
        });
    </script>

    <!-- Plugins JS start-->
    <script src="../assets/js/modal-animated.js"></script>
    <script src="../assets/js/datatable/datatables/jquery.dataTables.min.js"></script>
    <script src="../assets/js/datatable/datatables/datatable.custom.js"></script>
    <script src="../assets/js/tooltip-init.js"></script>
    <script src="../assets/js/modal-animated.js"></script>
    <script src="../assets/js/datatable/datatables/jquery.dataTables.min.js"></script>
    <script src="../assets/js/datatable/datatable-extension/dataTables.buttons.min.js"></script>
    <script src="../assets/js/datatable/datatable-extension/jszip.min.js"></script>
    <script src="../assets/js/datatable/datatable-extension/buttons.colVis.min.js"></script>
    <script src="../assets/js/datatable/datatable-extension/pdfmake.min.js"></script>
    <script src="../assets/js/datatable/datatable-extension/vfs_fonts.js"></script>
    <script src="../assets/js/datatable/datatable-extension/dataTables.autoFill.min.js"></script>
    <script src="../assets/js/datatable/datatable-extension/dataTables.select.min.js"></script>
    <script src="../assets/js/datatable/datatable-extension/buttons.bootstrap4.min.js"></script>
    <script src="../assets/js/datatable/datatable-extension/buttons.html5.min.js"></script>
    <script src="../assets/js/datatable/datatable-extension/buttons.print.min.js"></script>
    <script src="../assets/js/datatable/datatable-extension/dataTables.bootstrap4.min.js"></script>
    <script src="../assets/js/datatable/datatable-extension/dataTables.responsive.min.js"></script>
    <script src="../assets/js/datatable/datatable-extension/responsive.bootstrap4.min.js"></script>
    <script src="../assets/js/datatable/datatable-extension/dataTables.keyTable.min.js"></script>
    <script src="../assets/js/datatable/datatable-extension/dataTables.colReorder.min.js"></script>
    <script src="../assets/js/datatable/datatable-extension/dataTables.fixedHeader.min.js"></script>
    <script src="../assets/js/datatable/datatable-extension/dataTables.rowReorder.min.js"></script>
    <script src="../assets/js/datatable/datatable-extension/dataTables.scroller.min.js"></script>
    <script src="../assets/js/datatable/datatable-extension/custom.js"></script>
}