Viho/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Viho.web.DataDB;
using Quartz;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Quartz.Impl;
using System.Threading.Tasks;
using Viho.Models;
using Viho.web.Models;
using System.Security.Claims;
using Newtonsoft.Json;

namespace Viho.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        private readonly DbRentalContext _context;

        public class DashboardViewModel
        {
            public List<TbTenant> Tenants { get; set; }
            public List<TbLocation> PendingLocations { get; set; }
        }

        public DashboardController(DbRentalContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            ViewBag.FullName = HttpContext.Session.GetString("FullName");

            if (User.Identity.IsAuthenticated)
            {
                // User is authenticated, check the role and redirect accordingly
                var userRole = User.Claims.FirstOrDefault(c => c.Type == "URoleid")?.Value;
                if (userRole == "3") // Admin
                {
                    return RedirectToAction("AdminDashboard");
                }
                else if (userRole == "4") // Investor
                {
                    return RedirectToAction("InvestorDashboard");
                }
                // If the role is not 3 (Admin) or 4 (Investor), you can redirect to an appropriate page
                return RedirectToAction("Unauthorized");
            }

            // User is not authenticated, redirect to login page
            return RedirectToAction("Login", "Account");

           
        }



        private List<(DateTime Date, double TotalSales)> GetSalesTimeline()
        {
            var salesTimeline = _context.TbSales
                .GroupBy(s => new { s.SDate.Year, s.SDate.Month })
                .OrderBy(g => g.Key.Year).ThenBy(g => g.Key.Month)
                .Select(g => new
                {
                    Date = new DateTime(g.Key.Year, g.Key.Month, 1),
                    TotalSales = g.Sum(s => s.SAmountIn ?? 0)
                })
                .ToList();

            return salesTimeline.Select(s => (s.Date, s.TotalSales)).ToList();
        }



        public List<double> GetTotalSalesByYear()
        {
            var totalSalesByYear = _context.TbSales
                .GroupBy(s => s.SDate.Year)
                .OrderBy(g => g.Key)
                .Select(g => g.Sum(s => (s.SAmountIn ?? 0) - (s.SAmountOut ?? 0)))
                .ToList();

            return totalSalesByYear;
        }


        public List<double> GetTotalSalesByCategory()
        {
            var totalSalesByCategory = _context.TbSales
                .GroupBy(s => s.SCategory)
                .OrderBy(g => g.Key)
                .Select(g => g.Sum(s => s.SAmountIn ?? 0))
                .ToList();

            return totalSalesByCategory;
        }



        public List<double> GetTotalExpensesByYear()
        {
            var totalExpensesByYear = _context.TbSales
                .GroupBy(s => s.SDate.Year)
                .OrderBy(g => g.Key)
                .Select(g => g.Sum(s => s.SAmountOut ?? 0))
                .ToList();

            return totalExpensesByYear;
        }

        public double CalculateGrossProfit()
        {
            var totalSales = GetTotalSalesByYear().Sum();
            var totalExpenses = GetTotalExpensesByYear().Sum();
            var grossProfit = totalSales - totalExpenses;
            return grossProfit;
        }

        public double CalculateNetProfitMargin()
        {
            var totalSales = GetTotalSalesByYear().Sum();
            var totalExpenses = GetTotalExpensesByYear().Sum();
            var netProfitMargin = (totalSales - totalExpenses) / totalSales * 100;
            return Math.Round(netProfitMargin, 2);
            
        }

        public double CalculateExpenseToSalesRatio()
        {
            var totalSales = GetTotalSalesByYear().Sum();
            var totalExpenses = GetTotalExpensesByYear().Sum();
            var expenseToSalesRatio = (totalExpenses / totalSales) * 100;
            return Math.Round(expenseToSalesRatio, 2); // Round the ratio to two decimal places
        }

        public Dictionary<string, double> GetProfitByCategory()
        {
            var profitByCategory = _context.TbSales
                .GroupBy(s => s.SCategory)
                .OrderBy(g => g.Key)
                .Select(g => new
                {
                    Category = g.Key,
                    Profit = g.Sum(s => (s.SAmountIn ?? 0) - (s.SAmountOut ?? 0))
                })
                .ToDictionary(x => x.Category, x => x.Profit);

            return profitByCategory;
        }

        private double CalculateSalesGrowthRate()
        {
            var salesTimeline = GetSalesTimeline();

            if (salesTimeline.Count <= 1)
            {
                return 0.0; // Return 0 if there are no or only one data point
            }

            var initialSales = salesTimeline.First().TotalSales;
            var latestSales = salesTimeline.Last().TotalSales;

            var salesGrowthRate = (latestSales - initialSales) / initialSales * 100;

            return Math.Round(salesGrowthRate, 2);
        }

        private List<(DateTime Date, double Profit)> GetProfitByMonth()
        {
            var profitByMonth = _context.TbSales
                .GroupBy(s => new { s.SDate.Year, s.SDate.Month })
                .OrderBy(g => g.Key.Year)
                .ThenBy(g => g.Key.Month)
                .Select(g => new
                {
                    Date = new DateTime(g.Key.Year, g.Key.Month, 1),
                    Profit = g.Sum(s => (s.SAmountIn ?? 0) - (s.SAmountOut ?? 0))
                })
                .ToList();

            return profitByMonth.Select(s => (s.Date, s.Profit)).ToList();
        }

        private double CalculateProfitForCurrentMonth()
        {
            var currentDate = DateTime.Now;
            var profitByMonth = GetProfitByMonth();
            var currentMonthProfit = profitByMonth.FirstOrDefault(p => p.Date.Month == currentDate.Month && p.Date.Year == currentDate.Year);

            // If there is no profit data available for the current month, return 0.0
            if (currentMonthProfit.Equals(default((DateTime, double))))
            {
                return 0.0;
            }

            return currentMonthProfit.Profit;
        }


        // Method to retrieve the categories from the database
        public List<string> GetCategoriesFromDatabase()
        {
            var categories = _context.TbSales
                .Select(s => s.SCategory)
                .Distinct()
                .ToList();

            return categories;
        }


        public Dictionary<string, int> GetLossesByCategory()
        {
            var lossesByCategory = _context.TbSales
                .GroupBy(s => s.SCategory)
                .OrderBy(g => g.Key)
                .Select(g => new
                {
                    Category = g.Key,
                    Losses = g.Count(s => (s.SAmountIn ?? 0) - (s.SAmountOut ?? 0) < 0)
                })
                .ToDictionary(x => x.Category, x => x.Losses);

            return lossesByCategory;
        }

        private List<(string Month, double Profit, double Expenses)> GetProfitAndExpensesByMonth()
        {
            var profitAndExpensesByMonth = _context.TbSales
                .GroupBy(s => new { s.SDate.Year, s.SDate.Month })
                .OrderBy(g => g.Key.Year)
                .ThenBy(g => g.Key.Month)
                .Select(g => new
                {
                    Month = new DateTime(g.Key.Year, g.Key.Month, 1).ToString("MMM"),
                    Profit = g.Sum(s => (s.SAmountIn ?? 0) - (s.SAmountOut ?? 0)),
                    Expenses = g.Sum(s => s.SAmountOut ?? 0)
                })
                .ToList();

            return profitAndExpensesByMonth.Select(p => (p.Month, p.Profit, p.Expenses)).ToList();
        }

        public List<double> GetTotalExpensesByMonth()
        {
            var totalExpensesByMonth = _context.TbSales
                .GroupBy(s => new { s.SDate.Year, s.SDate.Month })
                .OrderBy(g => g.Key.Year)
                .ThenBy(g => g.Key.Month)
                .Select(g => g.Sum(s => s.SAmountOut ?? 0))
                .ToList();

            return totalExpensesByMonth;
        }






        [HttpPost]
        public IActionResult MarkPaymentMade(int landlordId)
        {
            // Find the landlord by ID
            var landlord = _context.TbLocations.FirstOrDefault(l => l.LId == landlordId);

            if (landlord != null)
            {
                // Update the payment status
                landlord.IsPaymentMade = true;
                _context.SaveChanges();
            }

            return RedirectToAction("Index");
        }
        [Authorize]
        [TypeFilter(typeof(RestrictAccessFilter))]
        public IActionResult AdminDashboard()
        {

            ViewBag.FullName = HttpContext.Session.GetString("FullName");
            // Retrieve data for the dashboard
            // Retrieve data for the dashboard
            List<double> TotalSalesByYear = GetTotalSalesByYear();
            List<double> TotalExpensesByYear = GetTotalExpensesByYear();
            List<double> TotalSalesByCategory = GetTotalSalesByCategory();
            List<(DateTime Date, double TotalSales)> salesTimeline = GetSalesTimeline();
            List<string> Categories = GetCategoriesFromDatabase();
            // Calculate profit for each month
            List<double> TotalProfitByMonth = new List<double>();
            List<double> TotalExpensesByMonth = GetTotalExpensesByMonth();

Viho/Controllers/TbUsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Viho.web.DataDB;
using System.Security.Cryptography;
using System.Text;
using Microsoft.AspNetCore.Authorization;




namespace Viho.web.Controllers
{
    [Authorize]
    public class TbUsersController : Controller
    {

        
        private readonly DbRentalContext _context;

        public TbUsersController(DbRentalContext context)
        {
            _context = context;
        }

        // GET: TbUsers
        public async Task<IActionResult> Index()
        {
            var dbRentalContext = _context.TbUsers.Include(t => t.URole);
            return View(await dbRentalContext.ToListAsync());
        }

        // GET: TbUsers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.TbUsers == null)
            {
                return NotFound();
            }

            var tbUser = await _context.TbUsers
                .Include(t => t.URole)
                .FirstOrDefaultAsync(m => m.UId == id);
            if (tbUser == null)
            {
                return NotFound();
            }

            return PartialView("_Details", tbUser);
        }

        // GET: TbUsers/Create
        public IActionResult Create()
        {
            ViewData["URoleid"] = new SelectList(_context.TbRoles, "RlId", "RlDesc");
            return View();
        }

        private string HashPassword(string password)
        {
            using (SHA256 sha256 = SHA256.Create())
            {
                byte[] hashedBytes = sha256.ComputeHash(Encoding.UTF8.GetBytes(password));

                StringBuilder builder = new StringBuilder();
                for (int i = 0; i < hashedBytes.Length; i++)
                {
                    builder.Append(hashedBytes[i].ToString("x2"));
                }

                return builder.ToString();
            }
        }

        // POST: TbUsers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UId,UUsername,UPass,UPhone,UEmail,URoleid")] TbUser tbUser)
        {
            if (ModelState.IsValid)
            {
                tbUser.UPass = HashPassword(tbUser.UPass);
                _context.Add(tbUser);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            string errors = string.Join("; ", ModelState.Values
                .SelectMany(x=>x.Errors)
                .Select(x=>x.ErrorMessage));  
            ModelState.AddModelError("", errors);
            ViewData["URoleid"] = new SelectList(_context.TbRoles, "RlId", "RlDesc",  tbUser.URoleid);
            return View(tbUser);
        }

        // GET: TbUsers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.TbUsers == null)
            {
                return NotFound();
            }

            var tbUser = await _context.TbUsers.FindAsync(id);
            if (tbUser == null)
            {
                return NotFound();
            }
            ViewData["URoleid"] = new SelectList(_context.TbRoles, "RlId", "RlDesc", tbUser.URoleid);
            return View(tbUser);
        }

        // POST: TbUsers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UId,UUsername,UPass,UPhone,UEmail,URoleid")] TbUser tbUser)
        {
            if (id != tbUser.UId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    tbUser.UPass = HashPassword(tbUser.UPass);
                    _context.Update(tbUser);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TbUserExists(tbUser.UId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["URoleid"] = new SelectList(_context.TbRoles, "RlId", "RlDesc", tbUser.URoleid);
            return View(tbUser);
        }

        // GET: TbUsers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.TbUsers == null)
            {
                return NotFound();
            }

            var tbUser = await _context.TbUsers
                .Include(t => t.URole)
                .FirstOrDefaultAsync(m => m.UId == id);
            if (tbUser == null)
            {
                return NotFound();
            }

            return View(tbUser);
        }

        // POST: TbUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.TbUsers == null)
            {
                return Problem("Entity set 'DbRentalContext.TbUsers' is null.");
            }

            var tbUser = await _context.TbUsers.FindAsync(id);
            if (tbUser != null)
            {
                _context.TbUsers.Remove(tbUser);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Index));
        }


        private bool TbUserExists(int id)
        {
          return (_context.TbUsers?.Any(e => e.UId == id)).GetValueOrDefault();
        }
    }
}

Viho/Views/TbUsers/Create.cshtml
@model Viho.web.DataDB.TbUser

@{
    ViewData["Title"] = "User & Roles Add";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Script{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}


<div class="page-body">
    <div class="container-fluid">
        <div class="page-header">
            <div class="row">
                <div class="col-sm-6">
                    <h3>User & Roles</h3>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a asp-controller="Dashboard" asp-action="Index">Home</a></li>
                        
                        <li class="breadcrumb-item">User & Roles</li>
                        <li class="breadcrumb-item active">Add User</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <!-- Container-fluid starts-->
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header pb-0">
                        <h5>Add User</h5><span>Add users and select their roles.</span>
                    </div>
                    <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <form asp-action="Create">
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                <div class="form-group">
                                    <label>Full Name</label>
                                        <input asp-for="UUsername" class="form-control" placeholder="Full Name" />
                                     <span asp-validation-for="UUsername" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label>Password</label>
                                        <input asp-for="UPass" type="password" class="form-control" placeholder="Password" />
                                    <span asp-validation-for="UPass" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label>Phone Number</label>
                                        <input asp-for="UPhone" class="form-control" placeholder="Phone Number" />
                                    <span asp-validation-for="UPhone" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label>Email Address</label>
                                        <input asp-for="UEmail" class="form-control" placeholder="Email Address" />
                                    <span asp-validation-for="UEmail" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label>User Role</label>
                                    <select asp-for="URoleid" class="form-control" asp-items="ViewBag.URoleid">
                                            <option value="">-- Select Role --</option>
                                    </select>
                                        <span asp-validation-for="URoleid" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <input type="submit" value="Create" class="btn btn-primary" />
                                </div>
                            </form>
                        </div>
                    </div>

                    <div>
                        <a asp-action="Index">Back to List</a>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
    <!-- Container-fluid Ends-->
</div>

Viho/Views/TbUsers/Delete.cshtml
@model Viho.web.DataDB.TbUser

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TbUser</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UUsername)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UUsername)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UPass)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UPass)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UPhone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UPhone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UEmail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UEmail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.URole)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.URole.RlId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="UId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
</body>
</html>

Viho/Views/TbUsers/Index.cshtml
@model IEnumerable<Viho.web.DataDB.TbUser>


@{
    ViewData["Title"] = "User & Roles";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var userRoleIdClaim = User.Claims.FirstOrDefault(c => c.Type == "URoleid");
    var userRoleId = userRoleIdClaim != null ? int.Parse(userRoleIdClaim.Value) : 0;
}

@section Script {
    <!-- Plugins JS start-->
    <script src="../assets/js/datatable/datatables/jquery.dataTables.min.js"></script>
    <script src="../assets/js/datatable/datatables/datatable.custom.js"></script>
    <script src="../assets/js/tooltip-init.js"></script>
    <!-- Plugins JS Ends-->
    <!-- Plugins JS start-->
    <script src="../assets/js/modal-animated.js"></script>
    <!-- Plugins JS Ends-->

    <script src="../assets/js/sweet-alert/sweetalert.min.js"></script>
    <script src="../assets/js/sweet-alert/app.js"></script>
    

    <script>
        function loadDetails(id) {
            $.ajax({
                url: '@Url.Action("Details", "TbUsers")',
                type: 'GET',
                data: { id: id },
                success: function (result) {
                    $('#modalContent').html(result);
                    $('#myModal').modal('show');
                },
                error: function () {
                    alert('Error occurred while loading details.');
                }
            });
        }

        function showDeleteConfirmation(id) {
            // Set the action URL for the delete form in the modal
            var deleteUrl = "/TbUsers/Delete/" + id;
            $("#deleteForm").attr("action", deleteUrl);

            // Open the modal
            $("#exampleModal").modal("show");
        }
    </script>


}

<style>
    .column-action {
        width: 280px; /* Set the desired width */
    }
</style>
<div class="page-body">
    <div class="container-fluid">
        <div class="page-header">
            <div class="row">
                <div class="col-sm-6">
                    <h3>User & Roles</h3>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a asp-controller="Dashboard" asp-action="Index">Home</a></li>
                        <li class="breadcrumb-item active">User & Roles</li>
                    </ol>
                </div>
                @if (userRoleId == 3)
                {
                    <div class="col-sm-6">
                        <!-- Create room Start-->
                        <div class="bookmark">
                            <ul>
                                <p class="text-end">
                                    <a asp-action="Create" class="btn btn-pill btn-primary btn-air-primary btn-primary-gradien">
                                        <i data-feather="user-plus"></i>
                                    </a>
                                </p>
                            </ul>
                        </div>
                        <!-- Create room Ends-->
                    </div>
                }
                else { }
            </div>
        </div>
    </div>
<!-- User Table  Starts-->
<div class="col-sm-12">
    <div class="card">
        <div class="card-header">
                <h5>Record of Users</h5><span>View, edit and delete users. Add Admin or Investor.</span>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="display" id="basic-1">
                    <thead>
                        <tr>
                            <th>
                                Username
                            </th>
                            
                            <th>
                                Phone Number
                            </th>
                            <th>
                                Email Address
                            </th>
                            <th>
                                User Role
                            </th>
                                @if (userRoleId == 3)
                                {
                                    <th class="column-action">
                                        Action
                                    </th>
                                }
                                else
                                {
                                    
                                }
                            </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.UUsername)
                                </td>
                                
                                <td>
                                    @Html.DisplayFor(modelItem => item.UPhone)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.UEmail)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.URole.RlDesc)
                                </td>
                                    @if (userRoleId == 3)
                                    {
                                        <td>

                                            <a asp-action="Edit" asp-route-id="@item.UId" class="btn btn-pill btn-secondary btn-air-secondary btn-secondary-gradient">
                                                Edit
                                            </a>



                                            <a onclick="loadDetails(@item.UId)" class="btn btn-pill btn-danger btn-air-warning btn-warning-gradien">
                                                View
                                            </a>
                                            <a onclick="showDeleteConfirmation(@item.UId)" class="btn btn-pill btn-danger btn-air-danger btn-danger-gradien">
                                                Delete
                                            </a>


                                        </td>
                                    }
    
                               else{}
                            </tr>
                        }
                            
                    </tbody>
                </table>
            </div>

                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="#exampleModal" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">Delete Confirmation</h5>
                                <button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <p style="color: red;">Are you sure you want to delete this item? Changes made cannot be reverted!</p>
                            </div>
                            <div class="modal-footer">
                                <button class="btn btn-secondary" type="button" data-bs-dismiss="modal">Cancel</button>
                                <form id="deleteForm" action="" method="post">
                                    <input type="submit" class="btn btn-danger" value="Delete" />
                                </form>
                            </div>
                        </div>
                    </div>
                </div>




        </div>
    </div>
</div>
    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">User Details</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body" id="modalContent">
                    <div class="card">
                        <div class="animate-widget">
                    <!-- Content will be loaded dynamically here -->
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Container-fluid Ends-->
</div>

Viho/Views/TbUsers/_Details.cshtml
<!-- Container-fluid starts-->
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                            <hr />
                            <p><b>Username:</b> @Model.UUsername</p>
                            <p><b>Phone Number:</b> @Model.UPhone</p>
                            <p><b>Password:</b> @Model.UPass</p>
                            <p><b>Email Address:</b> @Model.UEmail</p>
                            <p><b>User Role:</b> @Model.URole.RlDesc</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>