Viho/Controllers/TbLotsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Viho.web.DataDB;

namespace Viho.web.Controllers
{
    public class TbLotsController : Controller
    {
        private readonly DbRentalContext _context;

        public TbLotsController(DbRentalContext context)
        {
            _context = context;
        }

        // GET: TbLots
        public async Task<IActionResult> Index()
        {
            var lots = await _context.TbLots.ToListAsync();

            foreach (var lot in lots)
            {
                var investorCount = _context.TbInvestors.Count(i => i.ILot == lot.LotId);
                var investmentSum = _context.TbInvestors.Where(i => i.ILot == lot.LotId).Sum(i => i.IInvestment);

                if (investorCount == 3 || investmentSum >= 50000)
                {
                    lot.LotStatus = "Full";
                }
                else
                {
                    lot.LotStatus = "Free";
                }
            }

            await _context.SaveChangesAsync();

            return View(lots);
        }

        // GET: TbLots/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.TbLots == null)
            {
                return NotFound();
            }

            var tbLot = await _context.TbLots
                .FirstOrDefaultAsync(m => m.LotId == id);
            if (tbLot == null)
            {
                return NotFound();
            }

            return PartialView("Details", tbLot);
        }

        // GET: TbLots/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TbLots/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("LotId,LotName,LotStatus")] TbLot tbLot)
        {
            if (ModelState.IsValid)
            {
                tbLot.LotStatus = "Free";

                _context.Add(tbLot);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            return View(tbLot);
        }

        // GET: TbLots/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.TbLots == null)
            {
                return NotFound();
            }

            var tbLot = await _context.TbLots.FindAsync(id);
            if (tbLot == null)
            {
                return NotFound();
            }
            return View(tbLot);
        }

        // POST: TbLots/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("LotId,LotName,LotStatus")] TbLot tbLot)
        {
            if (id != tbLot.LotId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tbLot);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TbLotExists(tbLot.LotId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tbLot);
        }

        // GET: TbLots/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.TbLots == null)
            {
                return NotFound();
            }

            var tbLot = await _context.TbLots
                .Include(lot => lot.TbInvestors)
                .FirstOrDefaultAsync(m => m.LotId == id);

            if (tbLot == null)
            {
                return NotFound();
            }

            if (tbLot.TbInvestors.Count > 0)
            {
                TempData["WarningMessage"] = "Cannot delete lot with investors.";
                return RedirectToAction("Index"); // Redirect to the index page or any other appropriate page
            }

            return View(tbLot);
        }


        // POST: TbLots/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.TbLots == null)
            {
                return Problem("Entity set 'DbRentalContext.TbLots'  is null.");
            }
            var tbLot = await _context.TbLots.FindAsync(id);
            if (tbLot != null)
            {
                _context.TbLots.Remove(tbLot);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TbLotExists(int id)
        {
          return (_context.TbLots?.Any(e => e.LotId == id)).GetValueOrDefault();
        }
    }
}

Viho/Controllers/TbRoomsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Viho.web.DataDB;
using Microsoft.AspNetCore.Hosting;
using System.IO;


namespace Viho.web.Controllers
{
    public class TbRoomsController : Controller
    {
        private readonly DbRentalContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;



        public TbRoomsController(DbRentalContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: TbRooms
        public async Task<IActionResult> Index()
        {
            var dbRentalContext = _context.TbRooms.Include(t => t.RLocation);
            var locations = await _context.TbLocations.ToListAsync();

            // Retrieve additional fields for each location based on Lid
            var locationDetails = locations.Select(location => new
            {
                location.LId,
                location.LAddress,
                location.LImglayout1,
                location.LCode
            }).ToList();

            ViewBag.Locations = locations; // Set the ViewBag property with the locations
            ViewBag.LocationDetails = locationDetails; // Set the ViewBag property with the location details

            return View(await dbRentalContext.ToListAsync());
        }


        // GET: TbRooms/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.TbRooms == null)
            {
                return NotFound();
            }

            var tbRoom = await _context.TbRooms
                .Include(t => t.RLocation)
                .FirstOrDefaultAsync(m => m.RId == id);
            if (tbRoom == null)
            {
                return NotFound();
            }

            return PartialView("_Details", tbRoom);
        }

        // GET: TbRooms/Create
        public IActionResult Create()
        {
            ViewData["RLocationid"] = new SelectList(_context.TbLocations, "LId", "LAddress");
            return View();
        }

        // POST: TbRooms/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RId,RNo,RLocationid,RType,RPrice,RDepositAmount,RDesc,RStatus,RImg1,RImg2")] TbRoom tbRoom, IFormFile? RImg1)
        {
            if (ModelState.IsValid)
            {
                if (RImg1 != null && RImg1.Length > 0)
                {
                    string uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "Picture/Rooms/");
                    string uniqueFileName = Guid.NewGuid().ToString() + "_" + RImg1.FileName;
                    string filePath = Path.Combine(uploadsFolder, uniqueFileName);

                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        await RImg1.CopyToAsync(fileStream);
                    }

                    tbRoom.RImg1 = uniqueFileName;
                }

                _context.Add(tbRoom);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["RLocationid"] = new SelectList(_context.TbLocations, "LId", "LAddress", tbRoom.RLocationid);
            return View(tbRoom);
        }



        // GET: TbRooms/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.TbRooms == null)
            {
                return NotFound();
            }

            var tbRoom = await _context.TbRooms.FindAsync(id);
            if (tbRoom == null)
            {
                return NotFound();
            }
            ViewData["RLocationid"] = new SelectList(_context.TbLocations, "LId", "LAddress", tbRoom.RLocationid);
            return View(tbRoom);
        }

        // POST: TbRooms/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RId,RNo,RLocationid,RType,RPrice,RDepositAmount,RDesc,RStatus,RImg1,RImg2")] TbRoom tbRoom, IFormFile? RImg1)
        {
            if (id != tbRoom.RId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (RImg1 != null && RImg1.Length > 0)
                    {
                        string uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "Picture/Rooms/");

                        if (!string.IsNullOrEmpty(tbRoom.RImg1))
                        {
                            string previousFilePath = Path.Combine(uploadsFolder, tbRoom.RImg1);
                            if (System.IO.File.Exists(previousFilePath))
                            {
                                System.IO.File.Delete(previousFilePath);
                            }
                        }

                        string uniqueFileName = Guid.NewGuid().ToString() + "_" + RImg1.FileName;
                        string filePath = Path.Combine(uploadsFolder, uniqueFileName);

                        using (var fileStream = new FileStream(filePath, FileMode.Create))
                        {
                            await RImg1.CopyToAsync(fileStream);
                        }

                        // Update the image property
                        tbRoom.RImg1 = uniqueFileName;
                    }
                    else
                    {
                        // No new file uploaded, retain the existing value
                        tbRoom.RImg1 = _context.TbRooms.AsNoTracking().FirstOrDefault(t => t.RId == id)?.RImg1;
                    }

                    _context.Update(tbRoom);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TbRoomExists(tbRoom.RId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["RLocationid"] = new SelectList(_context.TbLocations, "LId", "LAddress", tbRoom.RLocationid);
            return View(tbRoom);
        }


        // GET: TbRooms/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.TbRooms == null)
            {
                return NotFound();
            }

            var tbRoom = await _context.TbRooms
                .Include(t => t.RLocation)
                .FirstOrDefaultAsync(m => m.RId == id);
            if (tbRoom == null)
            {
                return NotFound();
            }

            return View(tbRoom);
        }

        // POST: TbRooms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tbRoom = await _context.TbRooms.FindAsync(id);

            // Check if the room exists
            if (tbRoom == null)
            {
                return NotFound();
            }

            // Delete the image file if it exists
            if (!string.IsNullOrEmpty(tbRoom.RImg1))
            {
                string imagePath = Path.Combine(_webHostEnvironment.WebRootPath, "Picture/Rooms", tbRoom.RImg1);

                // Check if the image file exists before deleting
                if (System.IO.File.Exists(imagePath))
                {
                    System.IO.File.Delete(imagePath);
                }
            }

            _context.TbRooms.Remove(tbRoom);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TbRoomExists(int id)
        {
            return (_context.TbRooms?.Any(e => e.RId == id)).GetValueOrDefault();
        }
    }
}

Viho/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;

namespace Cuba.Controllers
{
    public class UserController : Controller
    {
        public IActionResult UserProfile()
        {
            return View();
        }
        public IActionResult UserEdit()
        {
            return View();
        }
        public IActionResult UserCards()
        {
            return View();
        }
    }
}

Viho/Views/Shared/IconMarkup.cshtml
<div class="icon-hover-bottom p-fixed fa-fa-icon-show-div opecity-0">
    <div class="container-fluid">
        <div class="row">
        <div class="icon-popup">
            <div class="close-icon"><i class="icofont icofont-close"></i></div>
            <div class="icon-first"><i class="icon-drupal fa-2x" id="icon_main"></i></div>
            <div class="icon-class">
            <label class="icon-title">Class</label><span id="fclass1">icon-drupal</span>
            </div>
            <div class="icon-last icon-last">
            <label class="icon-title">Markup</label>
            <div class="form-inline">
                <div class="form-group">
                <input class="inp-val form-control m-r-10" id="input_copy" type="text" value="" readonly="readonly">
                <button class="btn btn-primary notification" onclick="myFunction()">Copy text</button>
                </div>
            </div>
            </div>
        </div>
        </div>
    </div>
</div>

Viho/Views/Shared/_AdLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <partial name="_Style" />
</head>
<body>
    <partial name="_Loader" />
    <div class="page-wrapper compact-wrapper" id="pageWrapper">
        <div class="page-body-wrapper sidebar-icon">
            <partial name="_Header" />
            <partial name="_SidePanelAdmin" />
            @RenderBody()
            <partial name="IconMarkup" />
            <partial name="_Footer" />
        </div>
    </div>
    <partial name="_Script" />
    @RenderSection("Script", false)

</body>
</html>

Viho/Views/Shared/_DashboardLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Cuba admin is super flexible, powerful, clean &amp; modern responsive bootstrap 5 admin template with unlimited possibilities.">
    <meta name="keywords" content="admin template, Cuba admin template, dashboard template, flat admin template, responsive admin template, web app">
    <meta name="author" content="pixelstrap">
    <link rel="icon" href="~/assets/images/favicon.png" type="image/x-icon">
    <link rel="shortcut icon" href="~/assets/images/favicon.png" type="image/x-icon">
    <title> @ViewData["Title"] - Cuba - Premium Admin Template</title>
    <!-- Google font-->
    <link href="https://fonts.googleapis.com/css?family=Rubik:400,400i,500,500i,700,700i&amp;display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,500,500i,700,700i,900&amp;display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="~/assets/css/font-awesome.css">
    <!-- ico-font-->
    <link rel="stylesheet" type="text/css" href="~/assets/css/vendors/icofont.css">
    <!-- Themify icon-->
    <link rel="stylesheet" type="text/css" href="~/assets/css/vendors/themify.css">
    <!-- Flag icon-->
    <link rel="stylesheet" type="text/css" href="~/assets/css/vendors/flag-icon.css">
    <!-- Feather icon-->
    <link rel="stylesheet" type="text/css" href="~/assets/css/vendors/feather-icon.css">
    <!-- Plugins css start-->
    <link rel="stylesheet" type="text/css" href="~/assets/css/vendors/scrollbar.css">
    <link rel="stylesheet" type="text/css" href="~/assets/css/vendors/animate.css">
    <link rel="stylesheet" type="text/css" href="~/assets/css/vendors/chartist.css">
    <link rel="stylesheet" type="text/css" href="~/assets/css/vendors/date-picker.css">
    <link rel="stylesheet" type="text/css" href="~/assets/css/vendors/owlcarousel.css">
    <link rel="stylesheet" type="text/css" href="~/assets/css/vendors/prism.css">
    <!-- Plugins css Ends-->
    <!-- Bootstrap css-->
    <link rel="stylesheet" type="text/css" href="~/assets/css/vendors/bootstrap.css">
    <!-- App css-->
    <link rel="stylesheet" type="text/css" href="~/assets/css/style.css">
    <link id="color" rel="stylesheet" href="~/assets/css/color-1.css" media="screen">
    <!-- Responsive css-->
    <link rel="stylesheet" type="text/css" href="~/assets/css/responsive.css">
    <link rel="stylesheet" type="text/css" href="~/assets/css/responsive.css">
</head>
<body onload="startTime()">
    <div class="tap-top"><i data-feather="chevrons-up"></i></div>
    <div class="page-wrapper compact-wrapper" id="pageWrapper">
        <!-- Page Body Start-->
        <div class="page-body-wrapper">
            <partial name="_Header" />
            <partial name="_SidePenal" />
            @RenderBody();
            <partial name="_Footer" />
        </div>
    </div>
    <!-- latest jquery-->
    <script src="~/assets/js/jquery-3.5.1.min.js"></script>
    <!-- Bootstrap js-->
    <script src="~/assets/js/bootstrap/bootstrap.bundle.min.js"></script>
    <!-- feather icon js-->
    <script src="~/assets/js/icons/feather-icon/feather.min.js"></script>
    <script src="~/assets/js/icons/feather-icon/feather-icon.js"></script>
    <!-- scrollbar js-->
    <script src="~/assets/js/scrollbar/simplebar.js"></script>
    <script src="~/assets/js/scrollbar/custom.js"></script>
    <!-- Sidebar jquery-->
    <script src="~/assets/js/config.js"></script>
    <!-- Plugins JS start-->
    <script src="~/assets/js/sidebar-menu.js"></script>
    <script src="~/assets/js/chart/chartist/chartist.js"></script>
    <script src="~/assets/js/chart/chartist/chartist-plugin-tooltip.js"></script>
    <script src="~/assets/js/chart/knob/knob.min.js"></script>
    <script src="~/assets/js/chart/knob/knob-chart.js"></script>
    <script src="~/assets/js/chart/apex-chart/apex-chart.js"></script>
    <script src="~/assets/js/chart/apex-chart/stock-prices.js"></script>
    <script src="~/assets/js/notify/bootstrap-notify.min.js"></script>
    <script src="~/assets/js/dashboard/default.js"></script>
    <script src="~/assets/js/notify/index.js"></script>
    <script src="~/assets/js/datepicker/date-picker/datepicker.js"></script>
    <script src="~/assets/js/datepicker/date-picker/datepicker.en.js"></script>
    <script src="~/assets/js/datepicker/date-picker/datepicker.custom.js"></script>
    <script src="~/assets/js/prism/prism.min.js"></script>
    <script src="~/assets/js/clipboard/clipboard.min.js"></script>
    <script src="~/assets/js/counter/jquery.waypoints.min.js"></script>
    <script src="~/assets/js/counter/jquery.counterup.min.js"></script>
    <script src="~/assets/js/counter/counter-custom.js"></script>
    <script src="~/assets/js/custom-card/custom-card.js"></script>
    <script src="~/assets/js/owlcarousel/owl.carousel.js"></script>
    <script src="~/assets/js/dashboard/dashboard_2.js"></script>
    <script src="~/assets/js/typeahead/handlebars.js"></script>
    <script src="~/assets/js/typeahead/typeahead.bundle.js"></script>
    <script src="~/assets/js/typeahead/typeahead.custom.js"></script>
    <script src="~/assets/js/typeahead-search/handlebars.js"></script>
    <script src="~/assets/js/typeahead-search/typeahead-custom.js"></script>
    <script src="~/assets/js/tooltip-init.js"></script>
    <!-- Plugins JS Ends-->
    <!-- Theme js-->
    <script src="~/assets/js/script.js"></script>
    <script src="~/assets/js/theme-customizer/customizer.js"></script>
    <!-- login js-->
    <!-- Plugin used-->
</body>
</html>

Viho/Views/Shared/_SidePanelAdmin.cshtml
 <!-- Page Sidebar Start-->
<header class="main-nav">
    <div class="sidebar-user text-center">
        <a class="setting-primary" href="javascript:void(0)"><i data-feather="settings"></i></a><img class="img-90 rounded-circle" src="~/assets/images/dashboard/1.png" alt="">
        <div class="badge-bottom"><span class="badge badge-primary">New</span></div><a asp-controller="User" asp-action="UserProfile">
            <h6 class="mt-3 f-14 f-w-600">Hello @ViewBag.FullName</h6>
        </a>
        <p class="mb-0 font-roboto">Admin</p>
        <ul>
            <li>
                <span><span class="counter">19.8</span>k</span>
                <p>Follow</p>
            </li>
            <li>
                <span>2 year</span>
                <p>Experince</p>
            </li>
            <li>
                <span><span class="counter">95.2</span>k</span>
                <p>Follower </p>
            </li>
        </ul>
    </div>
    <nav>
        <div class="main-navbar">
            <div class="left-arrow" id="left-arrow"><i data-feather="arrow-left"></i></div>
            <div id="mainnav">
                <ul class="nav-menu custom-scrollbar">
                    <li class="back-btn">
                        <div class="mobile-back text-end"><span>Back</span><i class="fa fa-angle-right ps-2" aria-hidden="true"></i></div>
                    </li>
                    <li class="sidebar-main-title">
                        <div>
                            <h6>General</h6>
                        </div>
                    </li>

                    <li class="dropdown">
                        <a class="nav-link menu-title" href="javascript:void(0)"><i data-feather="home"></i><span>Dashboard</span></a>
                        <ul class="nav-submenu menu-content">
                            <li><a asp-controller="Dashboard" asp-action="Index">General</a></li>
                            <li><a asp-controller="TbSales1" asp-action="SalesDashboard">Sales DashBoard</a></li>
                            <li><a asp-controller="TbSales1" asp-action="SalesByCategoryAndMonth">Summary</a></li>
                        </ul>
                    </li>
                    <li><a class="nav-link menu-title link-nav" asp-controller="TbUsers" asp-action="Index"><i data-feather="users"></i><span>Users & Roles</span></a></li>
                    <li><a class="nav-link menu-title link-nav" asp-controller="TbTenants" asp-action="Index"><i data-feather="user-check"></i><span>Tenants</span></a></li>
                    <li><a class="nav-link menu-title link-nav" asp-controller="TbRooms" asp-action="Index"><i data-feather="home"></i><span>Rooms</span></a></li>
                    <li><a class="nav-link menu-title link-nav" asp-controller="TbLocations" asp-action="Index"><i data-feather="map-pin"></i><span>Location</span></a></li>
                    <li><a class="nav-link menu-title link-nav" asp-controller="Inventory" asp-action="Index"><i data-feather="database"></i><span>Inventory</span></a></li>
                    <li><a class="nav-link menu-title link-nav" asp-controller="TbAttendancesCleaner" asp-action="Index"><i data-feather="check-square"></i><span>Cleaner Attendance</span></a></li>
                    <li><a class="nav-link menu-title link-nav" asp-controller="TbSales1" asp-action="Index"><i data-feather="activity"></i><span>Finance</span></a></li>
                    
                    
                    
                    <li><a class="nav-link menu-title link-nav" asp-controller="SupportTicket" asp-action="SupportTicket"><i data-feather="headphones"></i><span>Support Ticket</span></a></li>
                </ul>
            </div>
            <div class="right-arrow" id="right-arrow"><i data-feather="arrow-right"></i></div>
        </div>
    </nav>
</header>
<!-- Page Sidebar Ends-->

Viho/Views/Shared/_SidePenal.cshtml
@using System.Security.Claims

@{
    var usernameClaim = Context.User.Claims.FirstOrDefault(c => c.Type == "Username");
    var username = usernameClaim?.Value;

    var userRoleIdClaim = User.Claims.FirstOrDefault(c => c.Type == "URoleid");
    var userRoleId = userRoleIdClaim != null ? int.Parse(userRoleIdClaim.Value) : 0;


}

<!-- Page Sidebar Start-->
<header class="main-nav">
    <div class="sidebar-user text-center">
        <a class="setting-primary" href="javascript:void(0)"><i data-feather="settings"></i></a><img class="img-90 rounded-circle" src="~/assets/images/dashboard/1.png" alt="">
        <div class="badge-bottom"><span class="badge badge-primary">New</span></div><a asp-controller="User" asp-action="UserProfile">
            <h6 class="mt-3 f-14 f-w-600">Hello @username</h6>
        </a>
        <p class="mb-0 font-roboto">@Context.User.FindFirst("RoleName")?.Value</p>
        
    </div>
    <nav>
        <div class="main-navbar">
            <div class="left-arrow" id="left-arrow"><i data-feather="arrow-left"></i></div>
            <div id="mainnav">
                <ul class="nav-menu custom-scrollbar">
                    <li class="back-btn">
                        <div class="mobile-back text-end"><span>Back</span><i class="fa fa-angle-right ps-2" aria-hidden="true"></i></div>
                    </li>
                    <li class="dropdown">
                        <a class="nav-link menu-title" href="javascript:void(0)"><i data-feather="home"></i><span>Dashboard</span></a>
                        <ul class="nav-submenu menu-content">
                            @if (userRoleId == 3)
                            {
                                <li><a asp-controller="Dashboard" asp-action="Index">General</a></li>
                            }
                            else
                            {
                                <li><a asp-controller="Dashboard" asp-action="Index">Sales</a></li>
                            }
                            @if (userRoleId == 3)
                            {
                                <li><a asp-controller="TbSales1" asp-action="SalesDashboard">Sales</a></li>
                            }else{}
                            <li><a asp-controller="TbInvestors" asp-action="InvDashboard">Share</a></li>
                        </ul>
                    </li>
                    <li><a class="nav-link menu-title link-nav" asp-controller="TbUsers" asp-action="Index"><i data-feather="users"></i><span>Users & Roles</span></a></li>
                    <li class="dropdown">
                        <a class="nav-link menu-title" href="javascript:void(0)"><i data-feather="dollar-sign"></i><span>Finance</span></a>
                        <ul class="nav-submenu menu-content">
                            <li><a asp-controller="TbPayments" asp-action="Index">Payment History</a></li>
                            <li><a asp-controller="TbSales1" asp-action="Index">Expenses</a></li>
                            <li><a asp-controller="TbSales1" asp-action="SalesByCategoryAndMonth">Sales Summary</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="nav-link menu-title" href="javascript:void(0)"><i data-feather="cloud"></i><span>Investor</span></a>
                        <ul class="nav-submenu menu-content">
                            <li><a asp-controller="TbInvestors" asp-action="Index">List</a></li>
                            <li><a asp-controller="TbLots" asp-action="Index">Lot</a></li>
                        </ul>
                    </li>
                    <li><a class="nav-link menu-title link-nav" asp-controller="TbTenants" asp-action="Index"><i data-feather="user-check"></i><span>Tenants</span></a></li>
                    <li><a class="nav-link menu-title link-nav" asp-controller="TbRooms" asp-action="Index"><i data-feather="home"></i><span>Rooms</span></a></li>
                    <li><a class="nav-link menu-title link-nav" asp-controller="TbLocations" asp-action="Index"><i data-feather="map-pin"></i><span>Location</span></a></li>
                    <li><a class="nav-link menu-title link-nav" asp-controller="Inventory" asp-action="Index"><i data-feather="database"></i><span>Inventory</span></a></li>
                    <li><a class="nav-link menu-title link-nav" asp-controller="TbAttendancesCleaner" asp-action="Index"><i data-feather="check-square"></i><span>Cleaner Attendance</span></a></li>
                </ul>
            </div>
            <div class="right-arrow" id="right-arrow"><i data-feather="arrow-right"></i></div>
        </div>
    </nav>
</header>
<!-- Page Sidebar Ends-->