Viho/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Viho.web.DataDB;
using Quartz;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Quartz.Impl;
using System.Threading.Tasks;
using Viho.Models;
using Viho.web.Models;
using System.Security.Claims;
using Newtonsoft.Json;

namespace Viho.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        private readonly DbRentalContext _context;

        public class DashboardViewModel
        {
            public List<TbTenant> Tenants { get; set; }
            public List<TbLocation> PendingLocations { get; set; }
        }

        public DashboardController(DbRentalContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            ViewBag.FullName = HttpContext.Session.GetString("FullName");

            if (User.Identity.IsAuthenticated)
            {
                // User is authenticated, check the role and redirect accordingly
                var userRole = User.Claims.FirstOrDefault(c => c.Type == "URoleid")?.Value;
                if (userRole == "3") // Admin
                {
                    return RedirectToAction("AdminDashboard");
                }
                else if (userRole == "4") // Investor
                {
                    return RedirectToAction("InvestorDashboard");
                }
                // If the role is not 3 (Admin) or 4 (Investor), you can redirect to an appropriate page
                return RedirectToAction("Unauthorized");
            }

            // User is not authenticated, redirect to login page
            return RedirectToAction("Login", "Account");

           
        }



        private List<(DateTime Date, double TotalSales)> GetSalesTimeline()
        {
            var salesTimeline = _context.TbSales
                .GroupBy(s => new { s.SDate.Year, s.SDate.Month })
                .OrderBy(g => g.Key.Year).ThenBy(g => g.Key.Month)
                .Select(g => new
                {
                    Date = new DateTime(g.Key.Year, g.Key.Month, 1),
                    TotalSales = g.Sum(s => s.SAmountIn ?? 0)
                })
                .ToList();

            return salesTimeline.Select(s => (s.Date, s.TotalSales)).ToList();
        }



        public List<double> GetTotalSalesByYear()
        {
            var totalSalesByYear = _context.TbSales
                .GroupBy(s => s.SDate.Year)
                .OrderBy(g => g.Key)
                .Select(g => g.Sum(s => (s.SAmountIn ?? 0) - (s.SAmountOut ?? 0)))
                .ToList();

            return totalSalesByYear;
        }


        public List<double> GetTotalSalesByCategory()
        {
            var totalSalesByCategory = _context.TbSales
                .GroupBy(s => s.SCategory)
                .OrderBy(g => g.Key)
                .Select(g => g.Sum(s => s.SAmountIn ?? 0))
                .ToList();

            return totalSalesByCategory;
        }



        public List<double> GetTotalExpensesByYear()
        {
            var totalExpensesByYear = _context.TbSales
                .GroupBy(s => s.SDate.Year)
                .OrderBy(g => g.Key)
                .Select(g => g.Sum(s => s.SAmountOut ?? 0))
                .ToList();

            return totalExpensesByYear;
        }

        public double CalculateGrossProfit()
        {
            var totalSales = GetTotalSalesByYear().Sum();
            var totalExpenses = GetTotalExpensesByYear().Sum();
            var grossProfit = totalSales - totalExpenses;
            return grossProfit;
        }

        public double CalculateNetProfitMargin()
        {
            var totalSales = GetTotalSalesByYear().Sum();
            var totalExpenses = GetTotalExpensesByYear().Sum();
            var netProfitMargin = (totalSales - totalExpenses) / totalSales * 100;
            return Math.Round(netProfitMargin, 2);
            
        }

        public double CalculateExpenseToSalesRatio()
        {
            var totalSales = GetTotalSalesByYear().Sum();
            var totalExpenses = GetTotalExpensesByYear().Sum();
            var expenseToSalesRatio = (totalExpenses / totalSales) * 100;
            return Math.Round(expenseToSalesRatio, 2); // Round the ratio to two decimal places
        }

        public Dictionary<string, double> GetProfitByCategory()
        {
            var profitByCategory = _context.TbSales
                .GroupBy(s => s.SCategory)
                .OrderBy(g => g.Key)
                .Select(g => new
                {
                    Category = g.Key,
                    Profit = g.Sum(s => (s.SAmountIn ?? 0) - (s.SAmountOut ?? 0))
                })
                .ToDictionary(x => x.Category, x => x.Profit);

            return profitByCategory;
        }

        private double CalculateSalesGrowthRate()
        {
            var salesTimeline = GetSalesTimeline();

            if (salesTimeline.Count <= 1)
            {
                return 0.0; // Return 0 if there are no or only one data point
            }

            var initialSales = salesTimeline.First().TotalSales;
            var latestSales = salesTimeline.Last().TotalSales;

            var salesGrowthRate = (latestSales - initialSales) / initialSales * 100;

            return Math.Round(salesGrowthRate, 2);
        }

        private List<(DateTime Date, double Profit)> GetProfitByMonth()
        {
            var profitByMonth = _context.TbSales
                .GroupBy(s => new { s.SDate.Year, s.SDate.Month })
                .OrderBy(g => g.Key.Year)
                .ThenBy(g => g.Key.Month)
                .Select(g => new
                {
                    Date = new DateTime(g.Key.Year, g.Key.Month, 1),
                    Profit = g.Sum(s => (s.SAmountIn ?? 0) - (s.SAmountOut ?? 0))
                })
                .ToList();

            return profitByMonth.Select(s => (s.Date, s.Profit)).ToList();
        }

        private double CalculateProfitForCurrentMonth()
        {
            var currentDate = DateTime.Now;
            var profitByMonth = GetProfitByMonth();
            var currentMonthProfit = profitByMonth.FirstOrDefault(p => p.Date.Month == currentDate.Month && p.Date.Year == currentDate.Year);

            // If there is no profit data available for the current month, return 0.0
            if (currentMonthProfit.Equals(default((DateTime, double))))
            {
                return 0.0;
            }

            return currentMonthProfit.Profit;
        }


        // Method to retrieve the categories from the database
        public List<string> GetCategoriesFromDatabase()
        {
            var categories = _context.TbSales
                .Select(s => s.SCategory)
                .Distinct()
                .ToList();

            return categories;
        }


        public Dictionary<string, int> GetLossesByCategory()
        {
            var lossesByCategory = _context.TbSales
                .GroupBy(s => s.SCategory)
                .OrderBy(g => g.Key)
                .Select(g => new
                {
                    Category = g.Key,
                    Losses = g.Count(s => (s.SAmountIn ?? 0) - (s.SAmountOut ?? 0) < 0)
                })
                .ToDictionary(x => x.Category, x => x.Losses);

            return lossesByCategory;
        }

        private List<(string Month, double Profit, double Expenses)> GetProfitAndExpensesByMonth()
        {
            var profitAndExpensesByMonth = _context.TbSales
                .GroupBy(s => new { s.SDate.Year, s.SDate.Month })
                .OrderBy(g => g.Key.Year)
                .ThenBy(g => g.Key.Month)
                .Select(g => new
                {
                    Month = new DateTime(g.Key.Year, g.Key.Month, 1).ToString("MMM"),
                    Profit = g.Sum(s => (s.SAmountIn ?? 0) - (s.SAmountOut ?? 0)),
                    Expenses = g.Sum(s => s.SAmountOut ?? 0)
                })
                .ToList();

            return profitAndExpensesByMonth.Select(p => (p.Month, p.Profit, p.Expenses)).ToList();
        }

        public List<double> GetTotalExpensesByMonth()
        {
            var totalExpensesByMonth = _context.TbSales
                .GroupBy(s => new { s.SDate.Year, s.SDate.Month })
                .OrderBy(g => g.Key.Year)
                .ThenBy(g => g.Key.Month)
                .Select(g => g.Sum(s => s.SAmountOut ?? 0))
                .ToList();

            return totalExpensesByMonth;
        }






        [HttpPost]
        public IActionResult MarkPaymentMade(int landlordId)
        {
            // Find the landlord by ID
            var landlord = _context.TbLocations.FirstOrDefault(l => l.LId == landlordId);

            if (landlord != null)
            {
                // Update the payment status
                landlord.IsPaymentMade = true;
                _context.SaveChanges();
            }

            return RedirectToAction("Index");
        }
        [Authorize]
        [TypeFilter(typeof(RestrictAccessFilter))]
        public IActionResult AdminDashboard()
        {

            ViewBag.FullName = HttpContext.Session.GetString("FullName");
            // Retrieve data for the dashboard
            // Retrieve data for the dashboard
            List<double> TotalSalesByYear = GetTotalSalesByYear();
            List<double> TotalExpensesByYear = GetTotalExpensesByYear();
            List<double> TotalSalesByCategory = GetTotalSalesByCategory();
            List<(DateTime Date, double TotalSales)> salesTimeline = GetSalesTimeline();
            List<string> Categories = GetCategoriesFromDatabase();
            // Calculate profit for each month
            List<double> TotalProfitByMonth = new List<double>();
            List<double> TotalExpensesByMonth = GetTotalExpensesByMonth();

Viho/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;

namespace Cuba.Controllers
{
    public class UserController : Controller
    {
        public IActionResult UserProfile()
        {
            return View();
        }
        public IActionResult UserEdit()
        {
            return View();
        }
        public IActionResult UserCards()
        {
            return View();
        }
    }
}

Viho/Views/User/UserCards.cshtml
@{
    ViewData["Title"] = "User Cards";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="page-body">
          <div class="container-fluid">
            <div class="page-header">
              <div class="row">
                <div class="col-sm-6">
                  <h3>User Cards</h3>
                  <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a asp-controller="Dashboard" asp-action="Index">Home</a></li>
                    <li class="breadcrumb-item">Users</li>
                    <li class="breadcrumb-item active">User Cards</li>
                  </ol>
                </div>
                <div class="col-sm-6">
                  <!-- Bookmark Start-->
                  <div class="bookmark">
                    <ul>
                      <li><a href="javascript:void(0)" data-container="body" data-bs-toggle="popover" data-placement="top" title="" data-original-title="Tables"><i data-feather="inbox"></i></a></li>
                      <li><a href="javascript:void(0)" data-container="body" data-bs-toggle="popover" data-placement="top" title="" data-original-title="Chat"><i data-feather="message-square"></i></a></li>
                      <li><a href="javascript:void(0)" data-container="body" data-bs-toggle="popover" data-placement="top" title="" data-original-title="Icons"><i data-feather="command"></i></a></li>
                      <li><a href="javascript:void(0)" data-container="body" data-bs-toggle="popover" data-placement="top" title="" data-original-title="Learning"><i data-feather="layers"></i></a></li>
                      <li><a href="javascript:void(0)"><i class="bookmark-search" data-feather="star"></i></a>
                        <form class="form-inline search-form">
                          <div class="form-group form-control-search">
                            <input type="text" placeholder="Search..">
                          </div>
                        </form>
                      </li>
                    </ul>
                  </div>
                  <!-- Bookmark Ends-->
                </div>
              </div>
            </div>
          </div>
          <!-- Container-fluid starts-->
          <div class="container-fluid user-card">
            <div class="row">
              <div class="col-md-6 col-lg-6 col-xl-4 box-col-6">
                <div class="card custom-card">
                  <div class="card-header"><img class="img-fluid" src="~/assets/images/user-card/1.jpg" alt=""></div>
                  <div class="card-profile"><img class="rounded-circle" src="~/assets/images/avtar/3.jpg" alt=""></div>
                  <ul class="card-social">
                    <li><a href="javascript:void(0)"><i class="fa fa-facebook"></i></a></li>
                    <li><a href="javascript:void(0)"><i class="fa fa-google-plus"></i></a></li>
                    <li><a href="javascript:void(0)"><i class="fa fa-twitter"></i></a></li>
                    <li><a href="javascript:void(0)"><i class="fa fa-instagram"></i></a></li>
                    <li><a href="javascript:void(0)"><i class="fa fa-rss"></i></a></li>
                  </ul>
                  <div class="text-center profile-details"><a asp-controller="User" asp-action="UserProfile">
                      <h4>Mark Jecno</h4></a>
                    <h6>Manager</h6>
                  </div>
                  <div class="card-footer row">
                    <div class="col-4 col-sm-4">
                      <h6>Follower</h6>
                      <h3 class="counter">9564</h3>
                    </div>
                    <div class="col-4 col-sm-4">
                      <h6>Following</h6>
                      <h3><span class="counter">49</span>K</h3>
                    </div>
                    <div class="col-4 col-sm-4">
                      <h6>Total Post</h6>
                      <h3><span class="counter">96</span>M</h3>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-md-6 col-lg-6 col-xl-4 box-col-6">
                <div class="card custom-card">
                  <div class="card-header"><img class="img-fluid" src="~/assets/images/user-card/2.jpg" alt=""></div>
                  <div class="card-profile"><img class="rounded-circle" src="~/assets/images/avtar/16.jpg" alt=""></div>
                  <ul class="card-social">
                    <li><a href="javascript:void(0)"><i class="fa fa-facebook"></i></a></li>
                    <li><a href="javascript:void(0)"><i class="fa fa-google-plus"></i></a></li>
                    <li><a href="javascript:void(0)"><i class="fa fa-twitter"></i></a></li>
                    <li><a href="javascript:void(0)"><i class="fa fa-instagram"></i></a></li>
                    <li><a href="javascript:void(0)"><i class="fa fa-rss"></i></a></li>
                  </ul>
                  <div class="text-center profile-details"><a asp-controller="User" asp-action="UserProfile">
                      <h4>Johan Deo</h4></a>
                    <h6>Designer</h6>
                  </div>
                  <div class="card-footer row">
                    <div class="col-4 col-sm-4">
                      <h6>Follower</h6>
                      <h3 class="counter">2578</h3>
                    </div>
                    <div class="col-4 col-sm-4">
                      <h6>Following</h6>
                      <h3><span class="counter">26</span>K</h3>
                    </div>
                    <div class="col-4 col-sm-4">
                      <h6>Total Post</h6>
                      <h3><span class="counter">96</span>M</h3>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-md-6 col-lg-6 col-xl-4 box-col-6">
                <div class="card custom-card">
                  <div class="card-header"><img class="img-fluid" src="~/assets/images/user-card/3.jpg" alt=""></div>
                  <div class="card-profile"><img class="rounded-circle" src="~/assets/images/avtar/11.jpg" alt=""></div>
                  <ul class="card-social">
                    <li><a href="javascript:void(0)"><i class="fa fa-facebook"></i></a></li>
                    <li><a href="javascript:void(0)"><i class="fa fa-google-plus"></i></a></li>
                    <li><a href="javascript:void(0)"><i class="fa fa-twitter"></i></a></li>
                    <li><a href="javascript:void(0)"><i class="fa fa-instagram"></i></a></li>
                    <li><a href="javascript:void(0)"><i class="fa fa-rss"></i></a></li>
                  </ul>
                  <div class="text-center profile-details"><a asp-controller="User" asp-action="UserProfile">
                      <h4>Dev John</h4></a>
                    <h6>Devloper</h6>
                  </div>
                  <div class="card-footer row">
                    <div class="col-4 col-sm-4">
                      <h6>Follower</h6>
                      <h3 class="counter">6545</h3>
                    </div>
                    <div class="col-4 col-sm-4">
                      <h6>Following</h6>
                      <h3><span class="counter">91</span>K</h3>
                    </div>
                    <div class="col-4 col-sm-4">
                      <h6>Total Post</h6>
                      <h3><span class="counter">21</span>M</h3>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-md-6 col-lg-6 col-xl-4 box-col-6">
                <div class="card custom-card">
                  <div class="card-header"><img class="img-fluid" src="~/assets/images/user-card/7.jpg" alt=""></div>
                  <div class="card-profile"><img class="rounded-circle" src="~/assets/images/avtar/16.jpg" alt=""></div>
                  <ul class="card-social">
                    <li><a href="javascript:void(0)"><i class="fa fa-facebook"></i></a></li>
                    <li><a href="javascript:void(0)"><i class="fa fa-google-plus"></i></a></li>
                    <li><a href="javascript:void(0)"><i class="fa fa-twitter"></i></a></li>
                    <li><a href="javascript:void(0)"><i class="fa fa-instagram"></i></a></li>
                    <li><a href="javascript:void(0)"><i class="fa fa-rss"></i></a></li>
                  </ul>
                  <div class="text-center profile-details"><a asp-controller="User" asp-action="UserProfile">
                      <h4>Johan Deo</h4></a>
                    <h6>Designer</h6>
                  </div>
                  <div class="card-footer row">
                    <div class="col-4 col-sm-4">
                      <h6>Follower</h6>
                      <h3 class="counter">2578</h3>
                    </div>
                    <div class="col-4 col-sm-4">
                      <h6>Following</h6>
                      <h3><span class="counter">26</span>K</h3>
                    </div>
                    <div class="col-4 col-sm-4">
                      <h6>Total Post</h6>
                      <h3><span class="counter">96</span>M</h3>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-md-6 col-lg-6 col-xl-4 box-col-6">
                <div class="card custom-card">
                  <div class="card-header"><img class="img-fluid" src="~/assets/images/user-card/5.jpg" alt=""></div>
                  <div class="card-profile"><img class="rounded-circle" src="~/assets/images/avtar/11.jpg" alt=""></div>
                  <ul class="card-social">
                    <li><a href="javascript:void(0)"><i class="fa fa-facebook"></i></a></li>
                    <li><a href="javascript:void(0)"><i class="fa fa-google-plus"></i></a></li>
                    <li><a href="javascript:void(0)"><i class="fa fa-twitter"></i></a></li>
                    <li><a href="javascript:void(0)"><i class="fa fa-instagram"></i></a></li>
                    <li><a href="javascript:void(0)"><i class="fa fa-rss"></i></a></li>
                  </ul>
                  <div class="text-center profile-details"><a asp-controller="User" asp-action="UserProfile">
                      <h4>Dev John</h4></a>
                    <h6>Devloper</h6>
                  </div>
                  <div class="card-footer row">
                    <div class="col-4 col-sm-4">
                      <h6>Follower</h6>
                      <h3 class="counter">6545</h3>
                    </div>
                    <div class="col-4 col-sm-4">
                      <h6>Following</h6>
                      <h3><span class="counter">91</span>K</h3>
                    </div>
                    <div class="col-4 col-sm-4">
                      <h6>Total Post</h6>
                      <h3><span class="counter">21</span>M</h3>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-md-6 col-lg-6 col-xl-4 box-col-6">
                <div class="card custom-card">
                  <div class="card-header"><img class="img-fluid" src="~/assets/images/user-card/6.jpg" alt=""></div>
                  <div class="card-profile"><img class="rounded-circle" src="~/assets/images/avtar/3.jpg" alt=""></div>
                  <ul class="card-social">
                    <li><a href="javascript:void(0)"><i class="fa fa-facebook"></i></a></li>
                    <li><a href="javascript:void(0)"><i class="fa fa-google-plus"></i></a></li>
                    <li><a href="javascript:void(0)"><i class="fa fa-twitter"></i></a></li>
                    <li><a href="javascript:void(0)"><i class="fa fa-instagram"></i></a></li>
                    <li><a href="javascript:void(0)"><i class="fa fa-rss"></i></a></li>
                  </ul>
                  <div class="text-center profile-details"><a asp-controller="User" asp-action="UserProfile">
                      <h4>Mark Jecno</h4></a>
                    <h6>Manager</h6>
                  </div>
                  <div class="card-footer row">
                    <div class="col-4 col-sm-4">
                      <h6>Follower</h6>
                      <h3 class="counter">9564</h3>
                    </div>
                    <div class="col-4 col-sm-4">
                      <h6>Following</h6>
                      <h3><span class="counter">49</span>K</h3>
                    </div>
                    <div class="col-4 col-sm-4">
                      <h6>Total Post</h6>
                      <h3><span class="counter">96</span>M</h3>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- Container-fluid Ends-->
        </div>